# Generated by Django 4.2.7 on 2024-02-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_department_patients_doctors_contactdata_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='description',
        ),
    ]
