# Generated by Django 4.2.7 on 2024-02-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contactdata_checked_patients_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactdata',
            name='Patients',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
