# Generated by Django 4.2.7 on 2024-03-04 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contactdata_patients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
